[project]
name = "welld"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-adk>=1.11.0",
]

[tool.ruff]
indent-width = 2
line-length = 120
